experiment:
  name: zinc20_sequence_pretrain
  stage: pretrain

model:
  type: sequence
  n_layer: 24
  n_head: 16
  n_embd: 1024
  dropout: 0.1
  bias: false

data:
  loader_type: sequence
  dataset: very_big_molecules_selfies_2
  block_size: 156
  batch_size: 32
  meta_path: datasets/tokenizer/meta_chembl_db_aa_2_proto4.pkl
  train_bin: /LUSTRE/users/pvaras/nanoGPT/data/very_big_molecules_selfies_2/train_zink_aa.bin
  val_bin: /LUSTRE/users/pvaras/nanoGPT/data/very_big_molecules_selfies_2/val_zink_aa.bin
  pad_token_id: 0

training:
  init_from: scratch
  init_ckpt_path: null
  target_tokens: 524288
  num_gpus: 4
  learning_rate: 3.0e-4
  min_lr: 1.0e-5
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.99
  grad_clip: 1.0
  max_iters: 10000
  lr_decay_iters: 10000
  warmup_iters: 100
  decay_lr: true

eval:
  eval_interval: 500
  eval_iters: 200
  eval_only: false
  always_save_checkpoint: false

logging:
  out_dir: experiments/pretrain
  checkpoint_name: ckpt_zinc_M.pt
  log_interval: 50
  wandb_log: false
  wandb_project: molecules-gpt
  wandb_run_name: molecules-gpt

system:
  device: cuda
  dtype: bfloat16
  backend: nccl
  compile: false