# =========================
# MODEL
# =========================
model:
  type: "sequence"
  module: "pockliggpt.models.model_sequence"
  checkpoint_path: "/LUSTRE/users/pvaras/sequence_gpt/out-models/ckpt_zink_chembl_cross_sequence.pt"

# =========================
# DATA
# =========================
data:
  smiles_csv: "zink_250k.csv"
  smiles_column: "smiles"
  
tokenizer:
  meta_path: datasets/tokenizer/meta_chembl_db_aa_2_proto4.pkl

# =========================
# RL
# =========================
rl:
  batch_size: 64
  lr: 3e-5
  prompt_size: 50
  prompt_batch_size: 256
  num_rollouts: 256
  epochs: 30
  ppo_epochs: 4
  kl_coef: 0.005
  gamma: 0.99
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.1
  vf_coef: 1.0

# =========================
# GENERATION
# =========================
generation:
  seq_length: 156
  max_new_tokens: 106
  top_k: 10
  temperature: 0.9

# =========================
# PROMPT
# =========================
prompt:
  format: "pocket_ligand"
  include_pocket_tokens: true
  include_pocket_embedding: false

# =========================
# CONDITIONING
# =========================
conditioning:
  pocket_str: "ASN ASP SER PHE GLY SER TRP ASN GLY GLY GLY PHE GLN THR GLY TYR GLU SER ALA TRP THR PRO LEU SER VAL GLU GLY THR ALA PHE LEU VAL TYR PHE TRP MET HIS GLY TYR"

# =========================
# REWARD
# =========================
reward:
  combiner: "mw_only"

# =========================
# SYSTEM
# =========================
system:
  train_device: "cuda:0"
  ref_device: "cuda:1"
  dtype: "bfloat16"

# =========================
# OUTPUT
# =========================
output:
  ppo_ckpt_path: "out-models/ckpt_zink_chembl_cross_sequence_bace.pt"
  loss_history_file: "loss_history_M.txt"
  save_trajectories: true